### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [riperjack/stunts_remake#2]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by riperjack** [comment]
Hello, 
source code is licensed under WTFPL. 
Car model is CC-BY [ Lamborghini Bravo model made by BDFSPACE69 ( https://www.blendswap.com/blends/view/73626 ) ].
Other 3D models ( barns, houses, ramps, etc. ) where extraced from the original game.
